FROM node:16
WORKDIR /app
COPY package.json /app/
COPY package-lock.json /app/
RUN npm ci

ARG APP__HOST
ARG APP__PORT
ARG APP__JWT_SECRET
ARG APP__JWT_TOKEN_EXPIRES_IN
ARG SEQUELIZE__DIALECT
ARG SEQUELIZE__LOGGING
ARG SEQUELIZE__HOST
ARG SEQUELIZE__USERNAME
ARG SEQUELIZE__PASSWORD
ARG SEQUELIZE__PORT
ARG SEQUELIZE__DATABASE
ARG SEQUELIZE__TIMEZONE
ARG SEQUELIZE__TIMESTAMPS

ENV APP__HOST=${APP__HOST}
ENV APP__PORT=${APP__PORT}
ENV APP__JWT_SECRET=${APP__JWT_SECRET}
ENV APP__JWT_TOKEN_EXPIRES_IN=${APP__HAPP__JWT_TOKEN_EXPIRES_INOST}
ENV SEQUELIZE__DIALECT=${SEQUELIZE__DIALECT}
ENV SEQUELIZE__LOGGING=${SEQUELIZE__LOGGING}
ENV SEQUELIZE__HOST=${SEQUELIZE__HOST}
ENV SEQUELIZE__USERNAME=${SEQUELIZE__USERNAME}
ENV SEQUELIZE__PASSWORD=${SEQUELIZE__PASSWORD}
ENV SEQUELIZE__PORT=${SEQUELIZE__PORT}
ENV SEQUELIZE__DATABASE=${SEQUELIZE__DATABASE}
ENV SEQUELIZE__TIMEZONE=${SEQUELIZE__TIMEZONE}
ENV SEQUELIZE__TIMESTAMPS=${SEQUELIZE__TIMESTAMPS}

COPY . /app/
