version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - .:/app
    ports:
      - 5000:5432
    env_file: .env
  node_js_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:3000
    depends_on:
      - db
