version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${SEQUELIZE__DATABASE}
      MYSQL_USER: ${SEQUELIZE__USERNAME}
      MYSQL_PASSWORD: ${SEQUELIZE__PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE__ROOT_PASSWORD}
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/var/lib/mysql:/var/lib/mysql
  nodejs:
    image: pavelinnokentevichgalanin/ooodepa_backend
    ports:
      - 80:5000
    command: npm run start
    depends_on:
      - db
